"""init_migration

Revision ID: bbf0a0070daf
Revises: 
Create Date: 2024-09-29 22:16:05.004236

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bbf0a0070daf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'files',
        sa.Column('file_pk', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('related_type', sa.String(), nullable=False),
        sa.Column('related_id', sa.Integer(), nullable=False),
        sa.Column('file_key', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "related_type IN ('user_photo', 'project_logo', 'task_attachment')",
            name='check_related_type',
        ),
        sa.PrimaryKeyConstraint('file_pk'),
    )
    op.create_index(
        'unique_related_type_related_id',
        'files',
        ['related_type', 'related_id'],
        unique=True,
        postgresql_where=sa.text("related_type != 'task_attachment'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'unique_related_type_related_id',
        table_name='files',
        postgresql_where=sa.text("related_type != 'task_attachment'"),
    )
    op.drop_table('files')
    # ### end Alembic commands ###
